#!/usr/bin/env bash

cleanup() {
  rm -rf $tmp_dir
}

on_error() {
  echo "An error occurred on line $1 in $0. Exiting."
  cleanup
  exit 1
}

trap 'on_error $LINENO' ERR

if !(git rev-parse --is-inside-work-tree >& /dev/null); then
    echo "Not inside a git repository, aborting"
    exit 1
fi

tmp_dir=$(mktemp -d -t git-housekeeping-XXXXX)
remotes=$tmp_dir/remotes
locals=$tmp_dir/locals
branchesToDelete=$tmp_dir/branchesToDelete

git remote prune origin

git branch -r --format "%(refname:lstrip=3)" > $remotes
git branch --format "%(refname:lstrip=2)" > $locals
cat $locals | grep -xv -f $remotes > $branchesToDelete || true

# -w checks word counts to ignore blank lines
if [ $(wc -w < $branchesToDelete) -gt 0 ];
then
    echo "$(wc -l < $branchesToDelete) branches without matching remote found, outputting to editor"
    echo "Waiting for editor to close"
    $VISUAL $branchesToDelete
    for branch in `cat $branchesToDelete`;
    do
        git branch -D $branch
    done
else
    echo "There are no branches to cleanup.";
fi

cleanup
